# HW05 - Exploring Trees/Graphs

YOUR NAME: Sanskruti Jadhav

In [1]:
# here is a list of edges:
T = [('Bob','Eve'),('Alice','Carol'),('Eve','Frank'),('Alice','Doug'),('Frank','Ginger'), \
         ('Eve','Howard'),('Carol','Irene'),('Frank','Jeff'),('Doug','Kathy'),('Bob','Luis'), \
         ('Alice','Bob'),('Bob','Mabel'),('Ginger','Norm'),('Howard','Oprah'),('Carol','Peter'), \
         ('Kathy','Queen'),('Mabel','Ursala'),('Luis','Ronald'),('Ginger','Sarah'),('Irene','Tom'), \
         ('Jeff','Vince'),('Peter','Wanda'),('Oprah','Xanthia'),('Norm','Yaakov'),('Luis','Zandra')]

print ('T has',len(T),'edges')
vertices = set()# This will only take unique values
for edge in T:
    s,t = edge
    vertices.add(s)
    vertices.add(t)
print ('T has',len(vertices),'vertices')

T has 25 edges
T has 26 vertices


In [2]:
print (vertices)

{'Carol', 'Tom', 'Ginger', 'Jeff', 'Kathy', 'Vince', 'Mabel', 'Bob', 'Peter', 'Sarah', 'Queen', 'Zandra', 'Ronald', 'Xanthia', 'Frank', 'Eve', 'Ursala', 'Oprah', 'Yaakov', 'Howard', 'Luis', 'Doug', 'Wanda', 'Irene', 'Norm', 'Alice'}


So this could be a tree. Now lets compute the number of parents for each vertex. The result confirms that we indeed have a tree and that the root is Alice (right?).

In [3]:
np = {} # a dictionary that maps vertex to the number of incoming edges
for v in vertices:
    np[v] = 0
for parent,child in T:
    np[child] += 1
print (np)

{'Carol': 1, 'Tom': 1, 'Ginger': 1, 'Jeff': 1, 'Kathy': 1, 'Vince': 1, 'Mabel': 1, 'Bob': 1, 'Peter': 1, 'Sarah': 1, 'Queen': 1, 'Zandra': 1, 'Ronald': 1, 'Xanthia': 1, 'Frank': 1, 'Eve': 1, 'Ursala': 1, 'Oprah': 1, 'Yaakov': 1, 'Howard': 1, 'Luis': 1, 'Doug': 1, 'Wanda': 1, 'Irene': 1, 'Norm': 1, 'Alice': 0}


We now construct a dictionary of pairs (p,c) where p is the parent of the list of children c

In [4]:
adjacency_map = {}
for v in vertices:
    adjacency_map[v] = []
for p,c in T:
    adjacency_map[p].append(c)
    #also do adjacency_map[c].append(p) to treat T as undirected edge list

print ("node and their children:")
for p in adjacency_map:
    print (p, ":", adjacency_map[p])

print ()
print (adjacency_map)

node and their children:
Carol : ['Irene', 'Peter']
Tom : []
Ginger : ['Norm', 'Sarah']
Jeff : ['Vince']
Kathy : ['Queen']
Vince : []
Mabel : ['Ursala']
Bob : ['Eve', 'Luis', 'Mabel']
Peter : ['Wanda']
Sarah : []
Queen : []
Zandra : []
Ronald : []
Xanthia : []
Frank : ['Ginger', 'Jeff']
Eve : ['Frank', 'Howard']
Ursala : []
Oprah : ['Xanthia']
Yaakov : []
Howard : ['Oprah']
Luis : ['Ronald', 'Zandra']
Doug : ['Kathy']
Wanda : []
Irene : ['Tom']
Norm : ['Yaakov']
Alice : ['Carol', 'Doug', 'Bob']

{'Carol': ['Irene', 'Peter'], 'Tom': [], 'Ginger': ['Norm', 'Sarah'], 'Jeff': ['Vince'], 'Kathy': ['Queen'], 'Vince': [], 'Mabel': ['Ursala'], 'Bob': ['Eve', 'Luis', 'Mabel'], 'Peter': ['Wanda'], 'Sarah': [], 'Queen': [], 'Zandra': [], 'Ronald': [], 'Xanthia': [], 'Frank': ['Ginger', 'Jeff'], 'Eve': ['Frank', 'Howard'], 'Ursala': [], 'Oprah': ['Xanthia'], 'Yaakov': [], 'Howard': ['Oprah'], 'Luis': ['Ronald', 'Zandra'], 'Doug': ['Kathy'], 'Wanda': [], 'Irene': ['Tom'], 'Norm': ['Yaakov'], 'Alice

In [5]:
print (5*"Hello!")

Hello!Hello!Hello!Hello!Hello!


In [6]:
# A recursive depth-first traversal of a tree defined by an adjacency_map
def print_tree_depth_first(parent, adjacency_map, level=0):
    print (level*'  ', parent)
    children = adjacency_map[parent]
    for child in children:
        print_tree_depth_first(child, adjacency_map, level+1)

root = 'Alice'
print_tree_depth_first(root, adjacency_map)

 Alice
   Carol
     Irene
       Tom
     Peter
       Wanda
   Doug
     Kathy
       Queen
   Bob
     Eve
       Frank
         Ginger
           Norm
             Yaakov
           Sarah
         Jeff
           Vince
       Howard
         Oprah
           Xanthia
     Luis
       Ronald
       Zandra
     Mabel
       Ursala


## Question 1
extend the breadth-first traversal to include the generation, so that the output is like below. Do this by also storing the generation in the queue.

In [7]:
from collections import deque 
am={"A":["B","D","E"], "B":["C"], "E":["F"], "D":[], "F":[], "C":[]}
            
# breadth-first traversal using a queue
def print_tree_breadth_first(root, adjacency_map):
    Q = deque()
    Q.append(root)
    while len(Q)>0:
        p = Q.popleft()
        print (p)
        children = adjacency_map[p]
        for child in children:
            Q.append(child)
           
            
print_tree_breadth_first("A", am)

def print_tree_breadth_first_by_generation(root, adjacency_map):
    Q = deque()
    Q.append((1,root))
    current_gen = 1
    new_gen = 1
    level =""
    
    while len(Q) > 0:
        p = Q.popleft()
        current_gen = p[0]
        parent = p[1]
        
        if (current_gen != new_gen): 
            print(new_gen, ":",level)
            new_gen += 1
            level = parent
            
        else:
            level= level + " " + parent
           
        children = adjacency_map[parent]
        
        for child in children:
            Q.append((current_gen+1,child))
            
    print(new_gen, ": ",level) 
                          
print_tree_breadth_first_by_generation("Alice", adjacency_map)

A
B
D
E
C
F
1 :  Alice
2 : Carol Doug Bob
3 : Irene Peter Kathy Eve Luis Mabel
4 : Tom Wanda Queen Frank Howard Ronald Zandra Ursala
5 : Ginger Jeff Oprah
6 : Norm Sarah Vince Xanthia
7 :  Yaakov


## Question 2
Write a function that checks if for the given directed graph (given by a list of edges E) root is connected to every other vertex.

In [8]:
def all_connected_to(edge_list, root):
    """ return true if you can reach all nodes in the graph given
    by a list of edges (edge_list) from root """
    # start by constructing set of vertices and the adjacency map
    trav = set()
    adjacency_map = {}
    for p,c in edge_list:
        if p not in adjacency_map: 
            adjacency_map[p]=[]
        if c not in adjacency_map:
            adjacency_map[c]=[]
        adjacency_map[p].append(c)
    
    s=[]
    s.append(root)
    while s:
        x=s.pop()
        trav.add(x)
        for e in adjacency_map[x]:
            if e not in trav:
                 s.append(e)
            
    if len(adjacency_map)== len(trav):
        return True
    else:
        return False
    

In [9]:
G = [("A","B"), ("B","C")]
print (all_connected_to(G, "A"))
G2 = [("1","2"), ("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G2, "A"))
print (all_connected_to(G2, "1"))
G3 = [("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G3, "C"))
# and our graph from above?
print (all_connected_to(T, "Alice"))

True
False
False
True
True


## Question 3
We now treat the the graph T from above as undirected (edges going in both directions) and construct a tree rooted in Bob. The tree will contain edges from a vertex to the parent and direct children. The result will tell us how far removed the vertices from our root Bob are.

In [41]:
root = 'Bob'

# construct adjacency for graph T:
adjacency_map = {}
for vertex in vertices:
    adjacency_map[vertex] = []
for edge in T:
    s,t = edge
    adjacency_map[s].append(t)
    adjacency_map[t].append(s)
    
print ("parents/children of Ginger:", adjacency_map['Ginger'])
print (adjacency_map)

# now create the adjacency map of the tree rooted in 'Bob'
tree = {}
#TODO: construct tree by using a queue
Q = deque()
Q.append(root)
while len(Q)>0:
    p = Q.popleft()
    tree[p]=[]
    children = adjacency_map[p]
    
    for child in children:
        if child not in tree:
            Q.append(child)
            tree[p].append(child)
    
print (tree)

parents/children of Ginger: ['Frank', 'Norm', 'Sarah']
{'Carol': ['Alice', 'Irene', 'Peter'], 'Tom': ['Irene'], 'Ginger': ['Frank', 'Norm', 'Sarah'], 'Jeff': ['Frank', 'Vince'], 'Kathy': ['Doug', 'Queen'], 'Vince': ['Jeff'], 'Mabel': ['Bob', 'Ursala'], 'Bob': ['Eve', 'Luis', 'Alice', 'Mabel'], 'Peter': ['Carol', 'Wanda'], 'Sarah': ['Ginger'], 'Queen': ['Kathy'], 'Zandra': ['Luis'], 'Ronald': ['Luis'], 'Xanthia': ['Oprah'], 'Frank': ['Eve', 'Ginger', 'Jeff'], 'Eve': ['Bob', 'Frank', 'Howard'], 'Ursala': ['Mabel'], 'Oprah': ['Howard', 'Xanthia'], 'Yaakov': ['Norm'], 'Howard': ['Eve', 'Oprah'], 'Luis': ['Bob', 'Ronald', 'Zandra'], 'Doug': ['Alice', 'Kathy'], 'Wanda': ['Peter'], 'Irene': ['Carol', 'Tom'], 'Norm': ['Ginger', 'Yaakov'], 'Alice': ['Carol', 'Doug', 'Bob']}
{'Bob': ['Eve', 'Luis', 'Alice', 'Mabel'], 'Eve': ['Frank', 'Howard'], 'Luis': ['Ronald', 'Zandra'], 'Alice': ['Carol', 'Doug'], 'Mabel': ['Ursala'], 'Frank': ['Ginger', 'Jeff'], 'Howard': ['Oprah'], 'Ronald': [], 'Zandra': 

Execute the following two blocks to check your result:

In [42]:
print_tree_depth_first(root, tree)

 Bob
   Eve
     Frank
       Ginger
         Norm
           Yaakov
         Sarah
       Jeff
         Vince
     Howard
       Oprah
         Xanthia
   Luis
     Ronald
     Zandra
   Alice
     Carol
       Irene
         Tom
       Peter
         Wanda
     Doug
       Kathy
         Queen
   Mabel
     Ursala


In [43]:
print_tree_breadth_first(root, tree)

Bob
Eve
Luis
Alice
Mabel
Frank
Howard
Ronald
Zandra
Carol
Doug
Ursala
Ginger
Jeff
Oprah
Irene
Peter
Kathy
Norm
Sarah
Vince
Xanthia
Tom
Wanda
Queen
Yaakov


## Question 4: n queens problem
Backtracking is the technique of recursively exploring the tree that contains all the possible solutions to a problem. Choose a systematic way to explore all the possible cases. This approach should reflect a rooted tree, and the backtracking approach is a depth-first search of the rooted tree. Whenever the search has found a solution or determined that there are no further solutions on the branches below the current vertex, backtrack to the preceeding vertex. 

A classic example of a problem that can be easily solved with this approach is the n queens problem.  This problem is to determine all the possible ways to place n nonattacking queens on an n-by-n chess board. The following code provides two helpful routines for this problem and illustrates one of the solutions for the 4 queens problem.

In [13]:
import numpy as np

def build_chessboard(N):
    chessboard = np.zeros((N,N))
    return chessboard

def print_chessboard(chessboard):
    N = len(chessboard)
    for r in range(N):
        for c in range(N):
            if chessboard[r,c] == 1:
                print ('Q', end="")
            else:
                print ('.', end="")
        print ()
    print ()

# generate an empty 4x4 chessboard:
chessboard = build_chessboard(4)
print (chessboard)

# Place 4 non-attacking queens on this board
chessboard[1,0] = 1
chessboard[3,1] = 1
chessboard[0,2] = 1
chessboard[2,3] = 1

# Pretty print the resulting board
print_chessboard(chessboard)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
..Q.
Q...
...Q
.Q..



Complete the following code to solve the n queens problem by returning the total number of solutions while printing only the first five solutions.

In [32]:
def n_queens(chessboard, column=0, count=0):
    """ given a partially filled <chessboard>, try to place a queen in column <column> and recursively fill the board.
    Finally return the number of solutions (added to <count>)"""
    N = len(chessboard)
    if column == N:
        if count < 5:
            print_chessboard(chessboard)
        return count+1
    
    # Examine all available squares in column <column>, place the queen, and 
    # mark all squares under attack by that queen.
    # Note: you can make a copy of a chessboard using chessboard.copy()
    
    for row in range(N):
        A = chessboard.copy()
        
        col =column
        if A[row, col] == 0:
            A[row,col] = 1
            A[row,col+1:N] = 3.14
            
            for j in range(1,N):
                
                if (row + j) < N and (col + j) < N :
                    A[row + j, col + j] = 3.14  
                    
                if (row - j) >=0 and (col + j) < N :
                    A[row - j, col + j] = 3.14                  
                    
            count = n_queens(A, col+1 , count)
    return count

chessboard = build_chessboard(5)
count = n_queens(chessboard)
print ("solutions: ", count)

Q....
...Q.
.Q...
....Q
..Q..

Q....
..Q..
....Q
.Q...
...Q.

..Q..
Q....
...Q.
.Q...
....Q

...Q.
Q....
..Q..
....Q
.Q...

.Q...
...Q.
Q....
..Q..
....Q

solutions:  10


In [38]:
# This example shows why .copy() is needed in your code above (reference semantics!)
def test(cb):
    cb[0,0]=1
    print_chessboard(cb)
    
chessboard = build_chessboard(4)
print_chessboard(chessboard)
test(chessboard.copy())# try chessboard.copy() instead
print_chessboard(chessboard)  # oooops!

....
....
....
....

Q...
....
....
....

....
....
....
....



In [39]:
import copy

# copy makes a copy of the outer-most object, but keeps the same references to the inner
# object.
a=[2,4,[6]]
print ("before: a=", a)

#not copying:
a=[2,4,[6]]
b=a
b[0]+=1
b[2][0]+=3
print ("after:  a=",a," b=", b, " (not copying)")

# using copy:
a=[2,4,[6]]
b=copy.copy(a)
b[0]+=1
b[2][0]+=3
print ("after:  a=",a," b=", b, " (using copy)")

# deepcopy also makes a copy of each contained element (recursively)
a=[2,4,[6]]
b=copy.deepcopy(a)
b[0]+=1
b[2][0]+=3
print ("after:  a=",a," b=", b, " (using deepcopy)")

before: a= [2, 4, [6]]
after:  a= [3, 4, [9]]  b= [3, 4, [9]]  (not copying)
after:  a= [2, 4, [9]]  b= [3, 4, [9]]  (using copy)
after:  a= [2, 4, [6]]  b= [3, 4, [9]]  (using deepcopy)
